# Generated by Django 5.0.3 on 2024-04-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('reason', models.CharField(default='', max_length=100)),
                ('reason_type', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default='', max_length=20)),
                ('time', models.TimeField(default='', max_length=10)),
                ('status', models.CharField(default='', max_length=20)),
                ('task_status', models.CharField(default='', max_length=20)),
                ('appointment_date', models.DateField(auto_now_add=True)),
                ('pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField()),
                ('customer_name', models.CharField(default='', max_length=100)),
                ('customer_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('mobileno', models.CharField(default='', max_length=15)),
                ('password', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('gender', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='', max_length=100)),
                ('product_id', models.IntegerField(default=1)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/order_images/')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_id', models.IntegerField()),
                ('customer_name', models.CharField(default='', max_length=20)),
                ('service_name', models.CharField(default='', max_length=100)),
                ('service_type', models.CharField(default='', max_length=50)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_payment', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=15)),
                ('description', models.CharField(max_length=500)),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/product_images/')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('work', models.CharField(max_length=50)),
                ('work_type', models.CharField(max_length=50)),
                ('work_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
